### PR TITLE
Minor improvements to R11 (3)

### PR DESCRIPTION
**Pull request by AerialMantis**
* Refactor `executor`, `executor_of`, `sender` and `sender_to` concept definitions.

### CODE REVIEW

**Comment by kirkshoop** [comment]
erics changes to sender, sender_to need to be merged with this..

**Comment by jaredhoberock** [comment]
I attempted to eliminate the conflicts, but I'm not sure if this is ready to merge due to Kirk's comment.

Has this PR merged with Eric's recent changes to sender & sender_to?

**Comment by AerialMantis** [comment]
Thanks, I’ll take a look once I get to a computer.

**Comment by AerialMantis** [comment]
I think this should be good to merge now.

**Comment by jaredhoberock** [comment]
Thanks! Merged.

**Pull request merged**
